services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./perico:/root/proyectos_hack
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - WPSCAN_TOKEN=${WPSCAN_TOKEN}
      - TZ=Europe/Madrid
    entrypoint: ./entrypoint.sh
    command: /bin/bash
    restart: unless-stopped
    networks:
      - kali_net

networks:
  kali_net:
    driver: bridge